services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:5000
    depends_on:
      - backend
    volumes:
      - ./client:/app
      - /app/node_modules

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - PORT=5000
      - MONGODB_URI=mongodb+srv://todouser:4DyN4gl4TG1UwO3g@todo-cluster.0fgbedh.mongodb.net/todoapp?retryWrites=true&w=majority&appName=todo-cluster
    volumes:
      - ./server:/app
      - /app/node_modules
