name: Deploy Todo App

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        
    - name: Install Backend Dependencies
      run: |
        cd server
        npm install
        
    - name: Install Frontend Dependencies
      run: |
        cd client
        npm install
        
    - name: Build Frontend
      run: |
        cd client
        npm run build

  docker:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Build and push Backend
      uses: docker/build-push-action@v3
      with:
        context: ./server
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/todo-backend:latest
        
    - name: Build and push Frontend
      uses: docker/build-push-action@v3
      with:
        context: ./client
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/todo-frontend:latest
